language: php
php:
  - 7.2
  - 7.3
  - 7.4
os:
  - linux
matrix:
  include:
    - php: 5.3
      dist: precise
    - php: 5.4.45
      dist: precise
    - php: 5.5
      dist: precise
    - php: 5.6
      dist: precise
    - php: 7.0
      dist: precise
    - php: 7.1
      dist: precise
before_install:
  - composer self-update
  - composer install

script: ./vendor/bin/phpunit --verbose --debug